### ISSUE TITLE
Is it possible to query a running server-less task for intermediate output?

### ISSUE THREAD

**Issue by tristanryerparke** [runpod/runpod-python#105]
For example let's say I'm using runpod serverless for training a gan on MNIST digits.
Often during training like this one would want to retrieve some visual data regarding the process, maybe a base64 image and other json data for performance metrics.
My actual use case is regarding potentially long-running inference with several epochs of refinement, but is something like this possible?
Best,
Tristan

**Comment by ashleykleynhans** [comment]
@tristanryerparke it is possible with [progress updates](https://docs.runpod.io/docs/worker-functions#progress-updates).

You can refer to my [example handler](https://github.com/ashleykleynhans/runpod-worker-progress/blob/main/rp_handler.py).

When you poll `/status`, the progress will appear in the `output` key of the response, for example:

```json
{
    "delayTime": 18378,
    "executionTime": 40213,
    "id": "2f1712c6-5ad7-4c9e-bf0b-9ea4ca20685c",
    "output": {
        "progress": "4/10"
    },
    "status": "IN_PROGRESS"
}
```
