### ISSUE TITLE
Minimal runpod python client

### ISSUE THREAD

**Issue by lkskstlr** [runpod/runpod-python#106]
Hi,
I really like the service and the python package is slim and neat 🚀  Just wrt. installation I would have a request :)

**Is your feature request related to a problem? Please describe.**
The full runpod install requires python 3.10 and multiple (large) dependencis. Both are problems in a constrained (e.g. AWS lambda) environment. It seems the `api_wrapper` doesn't use any of these features and could be standalone and slim.

**Describe the solution you'd like**
An install process which gives one the `api_wrapper` with minimal dependencies.

**Comment by justinmerrell** [comment]
Probably will not make it into the next release but the release after will have options similar to:

```bash
pip install runpod
pip install runpod[serverless]
pip install runpod[sdk/api]
pip install runpod[cli]
```

**Comment by justinmerrell** [comment]
Moving to a binary-based core that will be mounted into the pod, on track to have a thin SDK by version 2.0.0
