### ISSUE TITLE
[1.1.3] Docs outdated / not according to actual pip package

### ISSUE THREAD

**Issue by chris-aeviator** [runpod/runpod-python#108]
According to the docs these commands are supported: 

# Get all my pods
pods = runpod.get_pods()

# Get a specific pod
pod = runpod.get_pod(pod.id)

, 
however, 

```
>>> runpod.get_pods()
{'errors': [{'message': 'Something went wrong. Please try again later or contact support.', 'locations': [{'line': 2, 'column': 15}], 'extensions': {'code': 'GRAPHQL_PARSE_FAILED'}}]}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/korny/micromamba/envs/autoscaler-consul/lib/python3.11/site-packages/runpod/api_wrapper/ctl_commands.py", line 37, in get_pods
    raw_return = run_graphql_query(pod_queries.QUERY_POD)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/korny/micromamba/envs/autoscaler-consul/lib/python3.11/site-packages/runpod/api_wrapper/graphql.py", line 32, in run_graphql_query
    raise error.QueryError(response.json()["errors"][0]["message"])
runpod.error.QueryError: Something went wrong. Please try again later or contact support.
```

```


>>> runpod.get_pod("myid")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'runpod' has no attribute 'get_pod'. Did you mean: 'get_pods'?

```

**Comment by chris-aeviator** [comment]
sure!
```

❯ pip show runpod
Name: runpod
Version: 1.1.3
Summary: 🐍 | Python library for RunPod API and serverless worker SDK.
Home-page: https://github.com/runpod/runpod-python
Author: RunPod
Author-email: support@runpod.io
License: MIT
Location: /home/korny/micromamba/envs/autoscaler-consul/lib/python3.11/site-packages
Requires: aiohttp, backoff, boto3, fastapi, pillow, py-cpuinfo, python-dotenv, requests, tomli, tqdm-loggable
Required-by:
```

**Comment by axiom9** [comment]
I'm encountering this same issue currently. Please implement a fix for it.

**Comment by axiom9** [comment]
Thanks. When will `1.2.0` be released again? Any approximate timeline? 1 week, 2 weeks, 1 month...?

**Comment by justinmerrell** [comment]
Yesterday lol 

It is already out. https://pypi.org/project/runpod/

**Comment by chris-aeviator** [comment]
@justinmerrell I am still affected by this
Python 3.11


  |   File "/home/{…}/rent_gpu-DEBUG.py", line 101, in bid_for_runpod
  |     runpod_pod = runpod.create_pod(
  |                  ^^^^^^^^^^^^^^^^^^
  File "/home/{user}/micromamba/envs/{project}/lib/python3.11/site-packages/runpod/api/ctl_commands.py", line 92, in create_pod
  |     raw_response = run_graphql_query(
  |                    ^^^^^^^^^^^^^^^^^^
  |   File "/home/{user}/micromamba/envs/{project}lib/python3.11/site-packages/runpod/api/graphql.py", line 30, in run_graphql_query
  |     raise error.QueryError(response.json()["errors"][0]["message"])
  | runpod.error.QueryError: Something went wrong. Please try again later or
  | contact support.


❯ pip3 show runpod
Name: runpod
Version: 1.2.0
Summary: 🐍 | Python library for RunPod API and serverless worker SDK.
Home-page: https://github.com/runpod/runpod-python
Author: RunPod
Author-email: support@runpod.io
License: MIT
Location: /home/korny/micromamba/envs/autoscaler-consul/lib/python3.11/site-packages
Requires: aiohttp, aiohttp-retry, backoff, boto3, click, fastapi, pillow, py-cpuinfo, python-dotenv, requests, tomli, tqdm-loggable, urllib3
Required-by:

**Comment by justinmerrell** [comment]
This is a different issue; there is an error in the request formation. What is the full list of inputs you are using to create a new pod?

**Comment by falense** [comment]
I had this problem. For me the issue was that my Python3 was old. If you encounter this issue make sure that you have >= Python3.10

**Comment by justinmerrell** [comment]
Closing, existing open issues to address the backward compatibility.
