### ISSUE TITLE
create pods template features not supported

### ISSUE THREAD

**Issue by IridiumMaster** [runpod/runpod-python#123]
**Describe the bug**
templateId is supported in [[](url)](https://github.com/runpod/runpodctl/blob/main/doc/runpodctl_create_pod.md)

**To Reproduce**
1. pod = runpod.create_pod(name=myName,cloud_type="community",gpu_type_id="A100 80GB",gpu_count=1, templateId="2rg1vx16js")

**Expected behavior**
The api supports the same functions as the cli

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**

**Comment by justinmerrell** [comment]
Thanks to @tleyden for the PR to close this!
