### ISSUE TITLE
nvidia base image for GPU worker?

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [runpod/runpod-python#13]
Hi :wave: 

I was wondering how the [example `Dockerfile`](https://github.com/runpod/serverless-workers/blob/main/Tutorials/helloworld/Dockerfile) can run on a GPU without having any base image with cuda?

Thanks a lot

Cheers,

Fra

**Comment by justinmerrell** [comment]
In this particular case, the example does not require any GPU functionality. It is intended to be an architectural example. 

If you were building out a worker that required GPU you could use something like `ARG BASE_IMAGE=nvidia/cuda:11.6.2-cudnn8-devel-ubuntu20.04` as a starting point.
