### ISSUE TITLE
Support passing a template ID when starting a pod via createPod

### ISSUE THREAD

**Issue by tleyden** [runpod/runpod-python#145]
**Is your feature request related to a problem? Please describe.**

I don't see a way to specify a custom template ID when starting a pod via `createPod()`

**Describe the solution you'd like**

Add a new parameter to `createPod()` which accepts a template ID and adds it to the graphql mutation.

```
input_fields.append(f'templateId: "{template_id}"')
```

**Comment by tleyden** [comment]
@justinmerrell would it be possible to push a new version to pypi with this fix?  I'm having issues listing the git url as a dependency in my project, pip would be much easier

**Comment by justinmerrell** [comment]
Yes, working on a release, it will be cut either tonight or first thing in the morning.
