### ISSUE TITLE
runpod.start_pod(pod.id) don

### ISSUE THREAD

**Issue by Andy-TaiHL** [runpod/runpod-python#168]
runpod.start_pod(pod.id) don't work. 

After inserting the pod.id, the runpod.start_pod command doesn't work. There was an attribute error that says that "AttributeError: module 'runpod' has no attribute 'start_pod'". There was no problem with runpod.stop_pod(pod.id), and runpod.terminate_pod(pod.id). Just the start_pod function.

**Comment by ashleykleynhans** [comment]
Its called `resume_pod()` not `start_pod()`.
<img width="709" alt="Screenshot 2023-10-11 at 09 37 30" src="https://github.com/runpod/runpod-python/assets/886709/e29a8cbb-9b68-49d4-8792-44b3fa4772f2">

**Comment by Andy-TaiHL** [comment]
OK. Just tried it, but got another error: 
"QueryError: There are not enough free GPUs on the host machine to start this pod.". This is strange because I just entered 1 for the gpu_count parameter. I also checked that there are sufficient GPUs available in runpod, so that shouldn't be the problem.

**Comment by ashleykleynhans** [comment]
Probably no GPU available on the host your pod is on, best to check it in the GUI.
Although the GUI says there are GPUs available, you need it to be available on the host machine that your pod is on.
