### ISSUE TITLE
worker-utils.md - document doesn't exist

### ISSUE THREAD

**Issue by TimPietrusky** [runpod/runpod-python#169]
**Describe the bug**
I'm using the `rp_upload` and in the logs I see this when the `BUCKET_ENDPOINT_URL` is not configured:

```
2023-10-11T13:43:04.926575928Z If this is a live endpoint, please reference the following:
2023-10-11T13:43:04.926590519Z https://github.com/runpod/runpod-python/blob/main/docs/serverless/worker-utils.md
```

**To Reproduce**
1. Install `runpod`
2. Use `rp_upload` in your handler
3. Deploy the image to runpod
4. Use the `run` endpoint and see the message in the logs

**Expected behavior**
Link to the correct document.

**Comment by justinmerrell** [comment]
Thanks for catching this!

**Comment by TimPietrusky** [comment]
@justinmerrell you are welcome, thanks for the fix!
