### ISSUE TITLE
Unable to use API connection to use runpod Cloud GPU on a Colab notebook

### ISSUE THREAD

**Issue by Andy-TaiHL** [runpod/runpod-python#170]
Hi, I was attempting to run python codes in my Colab notebook but using the Cloud GPU on runpod. This project is about using LLM to generate text. 

I was able to create the pod using the codes. However, there are some technical problems:
1) the generated swagger link don't work.
2) I was also not able to generate a response from the code.
3) for runpod.create_pod(), the data_cener_id parameter will throw error if used. 

I believe some of the APIs don't work. Here are the codes that I used. Please help. Thanks.
=====
!pip install -Uqqq pip --progress-bar off
!pip install -qqq runpod==0.10.0 --progress-bar off
!pip install -qqq text-generation==0.6.0 --progress-bar off
!pip install -qqq requests==2.31.0 --progress-bar off

import requests
import runpod
from text_generation import Client

runpod.api_key = 'runpod api key'

gpu_count = 1

pod = runpod.create_pod(
    name="Llama-7b-chat",
    image_name="ghcr.io/huggingface/text-generation-inference:1.1.1",
    gpu_type_id="NVIDIA RTX A5000", #"NVIDIA RTX A4500"
    #data_center_id="EU-RO-1", ## the data_cener_id parameter will throw error if used.
    cloud_type="SECURE",
    docker_args="--model-id TheBloke/Llama-2-7b-chat-fp16",
    gpu_count=gpu_count,
    volume_in_gb=50,
    container_disk_in_gb=5,
    ports="80/http,29500/http",
    volume_mount_path="/data",
)
pod

from langchain.llms import HuggingFaceTextGenInference

inference_server_url = f'https://{pod["id"]}-80.proxy.runpod.net'
llm = HuggingFaceTextGenInference(
    inference_server_url=inference_server_url,
    max_new_tokens=1000,
    top_k=10,
    top_p=0.95,
    typical_p=0.95,
    temperature=0.1,
    repetition_penalty=1.03,
)

SERVER_URL = f'https://{pod["id"]}-80.proxy.runpod.net'
print(SERVER_URL)

print(f"Docs (Swagger UI) URL: {SERVER_URL}/docs") ## the swagger link don't work

DEFAULT_SYSTEM_PROMPT = """
You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe. Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature.

If a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information.
""".strip()

def generate_prompt(prompt: str, system_prompt: str = DEFAULT_SYSTEM_PROMPT) -> str:
    return f"""
[INST] <>
{system_prompt}
<>

{prompt} [/INST]
""".strip()

def make_request(prompt: str):
    data = {
        "inputs": prompt,
        "parameters": {"best_of": 1, "temperature": 0.01, "max_new_tokens": 512},
    }
    headers = {"Content-Type": "application/json"}

    return requests.post(f"{SERVER_URL}/generate", json=data, headers=headers)

print(response.json()["generated_text"].strip()) ## got error

**Comment by justinmerrell** [comment]
Was the pod created successfully? 

If this is a single file or did you wait for the pod to launch before you tried to send requests?

**Comment by Andy-TaiHL** [comment]
The pod was earlier created successfully, but I was not able to send requests to it. I tried to confirm it today, and everything doesn't work anymore because of some packages conflict. I am not even able to import it using Google Colab.
![error_runpod_20231013](https://github.com/runpod/runpod-python/assets/41158827/919d964c-675e-47fe-92f9-0f1efe64484e)

**Comment by justinmerrell** [comment]
Please let me know if this issue still exists with the latest versions of the SDK.
