### ISSUE TITLE
using Multiple GPU for LLM model  

### ISSUE THREAD

**Issue by Vish2427** [runpod/runpod-python#178]
**Problem**
I wanted to run my hugging face model over multiple gpu while deploying the model over runpod.

**Code used**
I used this code from documentation.
```
gpu_count = 2

pod = runpod.create_pod(
    name="Llama-7b-chat-brand_mapping",
    image_name="ghcr.io/huggingface/text-generation-inference:0.9.4",
    gpu_type_id="NVIDIA RTX A5000",
    data_center_id="EU-CZ-1",
    cloud_type="SECURE",
    docker_args="--model-id Vishal24/brand_mapping"
    gpu_count=gpu_count,
    volume_in_gb=50,
    container_disk_in_gb=30,
    ports="80/http,29500/http",
    volume_mount_path="/data",
)
pod
```
I got to understand that the docker image gets created using text-generation-interface.
But according to text-generation-interface to use multi gpu have to pass argument like  

`docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:1.1.0 --model-id $model`
**Question**
Now how do i pass "--gpus all" and "--shm-size 1g" into the docker_args parameter to run on multiple GPU.

**Comment by justinmerrell** [comment]
With runpod you do not need to pass `--gpus all` or `--shm-size 1g` we will take care of that for you.
