### ISSUE TITLE
Question about rp_metrics

### ISSUE THREAD

**Issue by ivoreis** [runpod/runpod-python#181]
**Is your feature request related to a problem? Please describe.**
Looking for more information about this library.

**Describe the solution you'd like**
Information of a particular code implementation/block

**Describe alternatives you've considered**
N/A

**Additional context**
Looking at the code base of some workers, there are references to a module called `rp_metrics` (ex: [vllm](https://github.com/runpod-workers/worker-vllm/blob/main/src/handler.py#L274-L277)). 

Where is that implementation, and is it open-sourced?

**Comment by justinmerrell** [comment]
@Jorghi12 Which fork has this functionality?

**Comment by ivoreis** [comment]
Looking at the dependency tree, it comes from the a1 fork. https://github.com/runpod/runpod-python/blob/a1/runpod/serverless/modules/rp_metrics.py. Thanks 👍🏼
