### ISSUE TITLE
Support Container Registry Auth in create_template

### ISSUE THREAD

**Issue by matankley** [runpod/runpod-python#209]
**Is your feature request related to a problem? Please describe.**
I'm using this sdk to create templates and pods. 
I create tempaltes that pull private images from my ghcr. Up until now, i've used the UI and chose my ghcr auth in the dropbox provided.

However, when I try to create_template within the sdk its no possible to pass any containerRegistryAuthId or any other container registry info , therefore im unable to create templates -> pods/

**Describe the solution you'd like**
I would like to pass container registry auth values in create_template function.

**Describe alternatives you've considered**
Currently I don't see any possible alternative to schematically generate templates within the sdk.

**Comment by matankley** [comment]
I created that fixes that, let me know if you are interested integrating that :)

**Comment by justinmerrell** [comment]
@matankley PRs are always welcome
