### ISSUE TITLE
API Wrapper Error Handling 

### ISSUE THREAD

**Issue by justinmerrell** [runpod/runpod-python#21]
When no GPU is available the following is returned:

Curl returns the error "{"errors":[{"message":"There are no longer any instances available with the requested specifications. Please refresh and try again.","path":["podFindAndDeployOnDemand"],"extensions":{"code":"RUNPOD"}}],"data":{"podFindAndDeployOnDemand":null}}"

This needs to be handled by the language API and returned.

**Comment by shibanovp** [comment]
Currently, you must print raw_response https://github.com/runpod/runpod-python/blob/b01e6b62d03273776692f6e88d9d57862c4d27cd/runpod/api_wrapper/ctl_commands.py#L37 


to visualize the error. It would be preferable to either raise an exception or implement another method of notifying the user.
