### ISSUE TITLE
How to pass variable and files from local

### ISSUE THREAD

**Issue by Vish2427** [runpod/runpod-python#213]
**Describe the bug**
I was wondering how do i pass my local files and the variables to the docker at the time of loading the pod

`docker run -v /path/to/local/data:/app/data -e MY_VARIABLE=my_value your_image_name`

I wanted to pass this file loaction : -v /path/to/local/data:/app/data
And the Variable : -e MY_VARIABLE=my_value

How do i do it here? As i think that it uses the command `docker run your_image_name` directly to run the image to load template.

Is there any parameter in runpod.create_pod() where i can pass this?

**Comment by ashleykleynhans** [comment]
Use the `env` parameter to add environment variables as key, value pairs.

**Comment by Vish2427** [comment]
> Use the `env` parameter to add environment variables as key, value pairs.

thanks for the reply, can please also tell me how do i pass my local file location too.

**Comment by justinmerrell** [comment]
You can not pass files in during pod creation, the easiest would be to create a custom docker image which has the files included and then launch a pod with that image. Alternatively you can use [runpodctl](https://github.com/runpod/runpodctl) once the pod is running to transfer in files.
