### ISSUE TITLE
bug: KeyError 'input'

### ISSUE THREAD

**Issue by dan-online** [runpod/runpod-python#23]
I've noticed recently that this error occurs within the library and thought I'd open an issue. It seems that input sometimes does not exist in job, specifically in old jobs that have been in the queue for a while. Therefore an exception occurs on this line: 
https://github.com/runpod/runpod-python/blob/main/runpod/serverless/work_loop.py#L44 
```py
> if job["input"] is None:
	 log.error(f"Job {job['id']} has no input parameter provided. Skipping this job.")
	 continue
```
The reason I opened an issue before a pull request is because input should always exist, even with old jobs, so I would like your input on this issue.

Thanks,
Dan

**Comment by justinmerrell** [comment]
Thank you for bringing this to our attention and submitting a PR. I just pushed a change to main that resolves this while returning an error message. Releasing later today.

**Comment by dan-online** [comment]
> Thank you for bringing this to our attention and submitting a PR. I just pushed a change to main that resolves this while returning an error message. Releasing later today. 

Awesome, I am curious why input would be empty though, was that a runpod issue that's been resolved?

**Comment by justinmerrell** [comment]
It was related to a situation that you observed with jobs that had been in the queue for a while. We have a TTL on for jobs, and if they sat in the queue for too long they would timeout, and then a blank job would be sent in.
