### ISSUE TITLE
Fail to install together with awscli due to the `colorama` dependency

### ISSUE THREAD

**Issue by Michaelvll** [runpod/runpod-python#242]
**Describe the bug**

I cannot install `runpod` with `awscli` together as the latter requires `colorama<0.4.5`.

**To Reproduce**
`pip install runpod >= 1.3.7 awscli`

**Additional context**
It is critical to install both packages for https://github.com/skypilot-org/skypilot/pull/2360

**Comment by Michaelvll** [comment]
> Works for `runpod==1.3.0` but does not work for any version `runpod>=1.3.1`.

Yes, it works with `1.3.0`, but since `runpod` has a bunch of API changes through those versions, e.g. the `~/.runpod/credentials.toml` is renamed to `~/.runpod/config.toml`, it would be nice that we can use the latest runpod package. ; )

**Comment by ashleykleynhans** [comment]
> > Works for `runpod==1.3.0` but does not work for any version `runpod>=1.3.1`.
> 
> Yes, it works with `1.3.0`, but since `runpod` has a bunch of API changes through those versions, e.g. the `~/.runpod/credentials.toml` is renamed to `~/.runpod/config.toml`, it would be nice that we can use the latest runpod package. ; )

Yep, was just trying to figure out where the problem started happening, seems `runpod` didn't have colorama in its requirements.txt prior to version 1.3.1.   I am not really sure why something like colorama needs versions to be locked.

**Comment by justinmerrell** [comment]
Thanks for the feedback guys, updated the requirements to be `colorama >= 0.2.5, < 0.4.5`
