### ISSUE TITLE
Runpod limits for serverless

### ISSUE THREAD

**Issue by nebis-software** [runpod/runpod-python#25]
Hi,
    I am currently unable to run a docker image (that runs nicely here) on the runpod serverless infrastructure... I continue getting a timeout error.
I am thinking I am hitting some limit, so my question: which are the runpod limits for serverless run? i.e. maximum "startup" time, maximum memory, maximum disk etc.

Thanks!
Luigi

**Comment by justinmerrell** [comment]
Have you installed the runpod Python library and started the serverless worker with your handler?

```python
runpod.serverless.start({"handler": you_handler_function})
```

When deploying a new endpoint and selecting a GPU you will see the system resources that come with the machine by hovering over the GPU button.
