### ISSUE TITLE
Job stuck in IN_QUEUE status after sending progress update

### ISSUE THREAD

**Issue by krzynio** [runpod/runpod-python#250]
I have simple code which is calling:

runpod.serverless.progress_update(self.job, f"{step_name};{total};{completed}")

After completion of the job I am left with:

{"delayTime":106401,"executionTime":4491,"id":"c395fafc-e87d-4a95-9241-42667a14d5fe-e1","output":"discrete_diarization;None;None","status":"IN_PROGRESS"}

When I am doing an update job is always left.stuck in IN_QUEUE status. 

I think that this could be a race condition as progress_update  is called in an async way and get's called after handler completes?

How to address it?

K.

**Comment by justinmerrell** [comment]
Looking at the job ID it is shown as being done. Are you using the python API wrapper to call the status, can you provide additional context or code, currently not enough to determine the issue.

**Comment by krzynio** [comment]
@justinmerrell here you go:

```
from model import pipeline
from pydub import AudioSegment
from schema import INPUT_VALIDATIONS
import os
import runpod
import tempfile

from runpod.serverless.utils.rp_validator import validate
from runpod.serverless.utils import download_files_from_urls, rp_cleanup, rp_debugger


class ProgressHook:
    def __init__(self, job):
        self.job = job

    def __call__(self, step_name, step_artifact, file, total=None, completed=None):
        runpod.serverless.progress_update(self.job, f"{step_name};{total};{completed}")


def run_job(job):
    job_input = job["input"]
    hook = ProgressHook(job)

    input_validation = validate(job_input, INPUT_VALIDATIONS)

    if "errors" in input_validation:
        return {"error": input_validation["errors"]}
    job_input = input_validation["validated_input"]

    audio_input = download_files_from_urls(job["id"], [job_input["audio"]])[0]

    random_file = tempfile.mkstemp(suffix=".wav")
    random_file_name = random_file[1]

    sound = AudioSegment.from_file(audio_input)
    sound.export(
        random_file_name,
        format="wav",
        bitrate="16k",
        parameters=["-ac", "1", "-c:a", "pcm_s16le"],
    )

    diarization = pipeline(random_file_name, hook=hook)
    speaker_results = [
        {"speaker": label, "start": segment.start, "end": segment.end}
        for segment, _, label in diarization.itertracks(yield_label=True)
    ]

    rp_cleanup.clean(["input_objects"])
    os.remove(random_file_name)

    return {"speaker_results": speaker_results}


runpod.serverless.start({"handler": run_job})
```

**Comment by justinmerrell** [comment]
How are you checking the status?

**Comment by krzynio** [comment]
I am using /status REST call to check the status

**Comment by justinmerrell** [comment]
Via cURL, postman SDK? 

May you provide screenshots of the full call?

**Comment by krzynio** [comment]
curl --header 'authorization: [token]' https://api.runpod.ai/v2/4...e/status/c395fafc-e87d-4a95-9241-42667a14d5fe-e1

**Comment by justinmerrell** [comment]
Dug into it and working to deploy a fix, thank you for reporting this and providing the context.

**Comment by krzynio** [comment]
@justinmerrell Thanks, 

I have added 1 second "sleep" before return at the end of run_job function and it is working properly, confirming that this was indeed some kind a race condition. Let me know when to remove this "fix" :)

**Comment by justinmerrell** [comment]
@krzynio We have resolved this issue in production and once jobs are marked as done will not be able to revert to the in-progress status. If you are on Discord, please send me a DM with your RunPod email and mention this issue, I'd like to provide you with some credits for your troubles and for helping to bring this to our attention.
