### ISSUE TITLE
Remove "test-" prefix from the job id

### ISSUE THREAD

**Issue by holwech** [runpod/runpod-python#267]
Is there any reason why "test-" is prepended to the job id in local dev? 

In my opinion, local dev should be as similar as possible to production. By prepending "test-" it's not possible to store this as a UUID in the a database for example without including custom logic. Unless there is a specific reason for this prefix, I suggest removing it.

**Comment by justinmerrell** [comment]
Job IDs are strings, not true UUID format. Your application should be handling strings for the job IDs; if this is still causing issues, please let me know, and I can review it.
