### ISSUE TITLE
mirror curl api

### ISSUE THREAD

**Issue by manu-pai** [runpod/runpod-python#3]
Looks like this is a new project just getting started.  Would be great if the simple runpod curl/cli commands were part of the lib like the https://github.com/runpod/runpodctl

**Comment by zhl146** [comment]
Hey, not sure what you mean. This one is actually packaged in pypi, so it's meant to be pip installed when building runpod workers.

**Comment by manu-pai** [comment]
I think what I'm looking for (and may be already done) is something that does these things:

`
```python
runpod-cli  startPod --params (...)   -myAPIKey   
```
and also or can be imported in python (e.g.)
```python
import runpod
runpod.setAPIKey( myAPIKey) # can be passed directly or could be loaded from env vars..
....
id = runpod.startPod( ...)

... interact with pod while running via remote connection (app dependant)....

runpod.stopPod(id)
```

I know there is the go based cli tool but figured having a python wrapped version was probably in the works to.

**Comment by zhl146** [comment]
Gotcha, you can look at https://github.com/opentensor/RunPodPy, but it hasn't been updated in a while.

We will likely add this functionality into our utility SDK, but we dont have it quite ready yet!

**Comment by justinmerrell** [comment]
Basic pod control functionality introduced in 0.9.3
