### ISSUE TITLE
Update & delete registry auth credentials

### ISSUE THREAD

**Issue by mwojcik-numlabs** [runpod/runpod-python#317]
**Is your feature request related to a problem? Please describe.**
We're using RunPod pods to train AI models based on our Docker images, which we store in ECR. The ECR credentials expire every 12 hours, so we need to update the token in the defined credentials setup. We'd like to have it done automatically, with our scripts. Currently, there's no API-based option to modify the existing auth credentials, only to create a new one.

**Describe the solution you'd like**
It would be nice to have two methods:
* `update_registry_auth_credentials(creds_id: str, user: str, password: str)` that allows the user to update the object with the provided credentials,
* `delete_registry_auth_credentials(creds_id: str)` that allows the user to delete the credentials setup.

**Describe alternatives you've considered**
If the credentials could be provided directly in `runpod.create_pod()`, without creating a separate template & credentials setup, we wouldn't need separate methods to manage credentials then. The credentials would be temporary - they wouldn't be kept in the user account, they'd only be used within the single pod.

**Comment by Yhlong00** [comment]
we have graphql api, you could try to use this for right now:

```js
// update key:
mutation UpdateRegistryAuth($input: UpdateRegistryAuthInput) {
  updateRegistryAuth(input: $input) {
    id
    name
  }
}

// input
{
  "input": {
    "id": "your_auth_id",
    "username": "username",
    "password": "password"
  }
}

// create key:
mutation SaveRegistryAuth($input: SaveRegistryAuthInput) {
  saveRegistryAuth(input: $input) {
    id
    name
  }
}

//input
{
  "input": {
    "name": "test",
    "username": "test",
    "password": "test"
  }
}


// delete key:
mutation DeleteRegistryAuth($registryAuthId: String) {
  deleteRegistryAuth(registryAuthId: $registryAuthId)
}

//input
{
  "registryAuthId": "your_auth_id"
}
```

**Comment by galen-runpod** [comment]
merged.

**Comment by js-9** [comment]
The official docs do not mention the delete and update mutations, only https://graphql-spec.runpod.io/#mutation-saveRegistryAuth .
