### ISSUE TITLE
Error while returning job result. | Object of type IntermediateValue is not JSON serializable

### ISSUE THREAD

**Issue by rinarakaki** [runpod/runpod-python#374]
**Describe the bug**
I'm trying to create a streaming handler. I `yield` a pydantic model for each iteration:

```py
from pydantic import BaseModel

class IntermediateValue(BaseModel):
    ...

def handler:
    for i in range(10):
        yield IntermediateValue(...)

start({"handler": handler})
```

When run locally there's no problem serialising pydantic model, but deployed and run on the remote serverless environment, it issues errors. Do you have any idea what causes this error?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gabewillen** [comment]
Hey @rinarakaki!

Try using `IntermediateValue(...).dict()` or `dict(IntermediateValue(...)` which should work during local development and when deployed.

**Comment by rinarakaki** [comment]
Thanks!
