### ISSUE TITLE
Webhook returns undefined / null / none body

### ISSUE THREAD

**Issue by pandas9** [runpod/runpod-python#381]
No idea where to post this but few hours ago this bug started happening where webhooks are sending undefined / null / none as a request body

```
const res = await fetch(https://api.runpod.ai/v2/.../run, {
      method: "POST",
      body: JSON.stringify(...),
        webhook: ${env.BACKEND_URL}/api/...,
      }),
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
        Authorization: ${env.RUNPOD_API_KEY},
      },
    });
```
    
this same request has been running for last month and worked fine, few hours ago webhook stopped working properly and returns undefined / null / none as a request body
    
getting job status works fine and returns expected result which is how we fixed it
    
hope this can get fixed soon, all the best

**Comment by deanq** [comment]
There was a blip in one of our releases last Tuesday. The issue persisted for a few hours before it was corrected.
