### ISSUE TITLE
Runpod on Google Colab : it used up my google disk space.

### ISSUE THREAD

**Issue by Mrin7** [runpod/runpod-python#41]
1.Followed the instruction on this blog : https://blog.runpod.io/how-to-connect-google-colab-to-runpod/ .
2.Connected to Jupyter Notebook.
3. How do we create an  SSH tunnel with port forwarding. Where are we supposed to create it? is it on local cmd, jupyter terminal, a different app altogether.
4. How do I connect my runpod to Google colab so that it stops eating my Google drive disk space. Even after paying you almost $4/hr to run my LLM models.

**Comment by justinmerrell** [comment]
You might be looking for the following: https://blog.runpod.io/how-to-achieve-true-ssh-on-runpod/

I am also closing out this issue as it us unrelated with this repo, for more general RunPod questions and support please reach out using one of the methods here: https://www.runpod.io/contact
