### ISSUE TITLE
Generator support changes incorrect

### ISSUE THREAD

**Issue by winglian** [runpod/runpod-python#57]
**Describe the bug**
from the original PR I submitted, the code looked like https://github.com/runpod/runpod-python/blob/f19342c33dff2ce15ff93f85f92ea80427fb614a/runpod/serverless/work_loop.py#L63-L71

and now is https://github.com/runpod/runpod-python/blob/main/runpod/serverless/work_loop.py#L66-L72

Logically, this is incorrect, as you can't test the handler function is a GeneratorType, you have to actually call the function, and only then can you determine if it is a GeneratorType from the result of the function call.

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="1512" alt="Screenshot 2023-07-13 at 2 09 31 AM" src="https://github.com/runpod/runpod-python/assets/381258/38fd9b8a-4c4b-431e-be69-15b67f5a5647">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by justinmerrell** [comment]
I'll add some tests to validate this, I recall that in the original PR I had to re-work it since it started to report all handlers as being generators.

**Comment by winglian** [comment]
@justinmerrell the linked PR #58 fixes this issue. It simply uses `inspect` so it doesn't have to execute the handler to determine if it's a generator.

**Comment by justinmerrell** [comment]
Changes are now in the release
