### ISSUE TITLE
S3 image ContentType differs from image format

### ISSUE THREAD

**Issue by off99555** [runpod/runpod-python#62]
I am not sure whether this is a bug. If I understand correctly, you are saving the image in arbitrary format e.g. jpeg, png, etc.
But you are setting `ContentType` to be fixed at `image/png`. Shouldn't the `ContentType` be the same as the format saved?
If this is not a bug, can you tell me the logic behind this?
https://github.com/runpod/runpod-python/blob/cf7dae6be8aa85caec6213105222e10e4900b225/runpod/serverless/utils/rp_upload.py#L99-L110

**Comment by justinmerrell** [comment]
This should be resolved in new versions of the SDK; please let me know if the issue persists.
