### ISSUE TITLE
Prepare for 1.0.0 Release 

### ISSUE THREAD

**Issue by justinmerrell** [runpod/runpod-python#64]
- [ ] Consider alternative names for `handler_fully_utilized ` 
- [ ] Check on the implementation of `job_in_progress`
- [ ] Document new functionality (multi-job and streaming)
- [ ] Close outstanding issues
- [ ] Marge/Close PRs
- [ ] Backwards compatibility down to 3.8

Test Validation:

- [ ] Deploy dev versions of endpoints with new worker

Bonus: 

- [ ] Social Media Card Image

**Comment by blakeblackshear** [comment]
Are there still plans to make this backwards compatible with older versions of python?

**Comment by justinmerrell** [comment]
It is still planned, just needed to cut a release before we got to that. I will separate this into another ticket to keep track of it easier.

**Comment by justinmerrell** [comment]
Closing with expanded compatibility added.
